global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'backend_1'
    scrape_interval: 5s

    static_configs:
      - targets: [ '104.45.76.88:9100', '104.45.76.88:9113' ]

  - job_name: 'backend_2'
    scrape_interval: 5s

    static_configs:
      - targets: [ '23.97.172.85:9100', '23.97.172.85:9113' ]

  - job_name: 'backend_3'
    scrape_interval: 5s

    static_configs:
      - targets: [ '137.117.229.68:9100', '137.117.229.68:9113' ]
#
#  - job_name: 'cadvisor'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['cadvisor:8080']
#
#  - job_name: 'prometheus'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['localhost:9090']
#
#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['pushgateway:9091']
#
#
#alerting:
#  alertmanagers:
#    - scheme: http
#      static_configs:
#        - targets:
#            - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']